### ISSUE TITLE
Windows Security Warnings

### ISSUE THREAD

**Issue by fkorax** [lacaulac/webex-anti-flash#1]
Windows Security/Defender detects the program as `Trojan:Win32/Wacatac.B!ml` and will not allow it to run.

**Comment by lacaulac** [comment]
That is super weird, I'm looking into it.

**Comment by lacaulac** [comment]
That is super weird, I'm looking into it.
Does that happen when using the binary releases or when compiling it yourself?

**Comment by lacaulac** [comment]
So, the binary release's files (both the dll and the exe) are being flagged by multiple antivirus solutions (virustotal: [dll](https://www.virustotal.com/gui/file/3b85edd956495484f453034e889bbdc7f9d720184ba8f544da8373fa31c3047c/detection) and [exe](https://www.virustotal.com/gui/file/86080a677d8d0cfe4a92a87565a2f35a473c3d58f91dd43669c812ba62383e0d/detection)).

I just downloaded the repo and recompiled it. When compiling in Release mode, the x64 version gets a few detections ([dll](https://www.virustotal.com/gui/file/7e8f20e740fb06e3dc394c367cb1f879ad59d32d113167f7bf625dddbe1b91df/detection) and [exe](https://www.virustotal.com/gui/file/7e8f20e740fb06e3dc394c367cb1f879ad59d32d113167f7bf625dddbe1b91df/detection)), and the x86 gets a few more ([dll](https://www.virustotal.com/gui/file/cae2ddd31860c0d4017373393327ee398647cd96c1d4bf85b8365869560073c1/detection) and [exe](https://www.virustotal.com/gui/file/a93e169b200a7e3735e8854136949638d7a995219b1697e7963e228978d1542d/detection)).
I don't really understand exactly why this happens, but my bet would be on the way WebexAntiFlash works, which is DLL injection via `LoadLibraryA` and `CreateRemoteThread` by the exe and the way the DLL places hooks on the WinAPI functions that are responsible for making the window flash in the taskbar.

I don't see any easy solutions to this except carefully reviewing the code if you're not confident in it not being malicious before recompiling it on your side, unfortunately.
